abstract: Get anonymously shared accounts for online services
author: Kentaro Kuribayashi <kentaro@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
name: WWW-BugMeNot
no_index: 
  directory: 
    - inc
    - t
requires: 
  URI: 0
  URI::Fetch: 0
version: 0.01
